Make ds2_snprintf and ds2_vsnprintf inline wrappers.
This creates ds2::Utils::Format and ds2::Utils::VFormat to replace
ds2_snprintf and ds2_vsnprintf. We also poison these symbols so the
compiler can warn about newly introduced uses.

For instance, clang does:

    /Users/sas/Source/ds2/Sources/main.cpp:265:3: error: attempt to use a poisoned identifier
      snprintf(foo, sizeof(foo), "foo %s", "bar");
      ^

and visual studio gives:

    Z:\Users\sas\Source\ds2\Sources\main.cpp(265): error C4995: 'snprintf': name was marked as #pragma deprecated [Z:\Users\sas\Source\ds2\build-WinStore-X86\ds2.vcxproj]